/*
 * Generated by STIR. Do not edit by hand.
 */

#include <sifteo/asset.h>

#pragma once

extern Sifteo::AssetGroup BootstrapAssets;
extern const Sifteo::AssetImage GraphemeCK;
extern const Sifteo::PinnedAssetImage BlackTile;
extern const Sifteo::AssetImage GraphemeD;
extern const Sifteo::AssetImage GraphemeDD;
extern const Sifteo::AssetImage GraphemeB;
extern const Sifteo::AssetImage Backgrounds;
extern const Sifteo::AssetImage Alphabet;
extern const Sifteo::AssetImage GraphemeC;
extern const Sifteo::AssetImage GraphemeBB;
extern const Sifteo::AssetImage GraphemeA;
extern const Sifteo::AssetImage GraphemeCH;
extern const Sifteo::AssetImage GraphemeE;
extern const Sifteo::AssetImage GraphemeF;
extern const Sifteo::AssetImage GraphemeFF;
extern const Sifteo::AssetImage GraphemePH;
extern const Sifteo::AssetImage GraphemeGH;
extern const Sifteo::AssetImage GraphemeG;
extern const Sifteo::AssetImage GraphemeH;
extern const Sifteo::AssetImage GraphemeI;
extern const Sifteo::AssetImage GraphemeJ;
extern const Sifteo::AssetImage GraphemeDGE;
extern const Sifteo::AssetImage GraphemeGE;
extern const Sifteo::AssetImage GraphemeK;
extern const Sifteo::AssetImage GraphemeL;
extern const Sifteo::AssetImage GraphemeLL;
extern const Sifteo::AssetImage GraphemeM;
extern const Sifteo::AssetImage GraphemeMM;
extern const Sifteo::AssetImage GraphemeMB;
extern const Sifteo::AssetImage GraphemeN;
extern const Sifteo::AssetImage GraphemeKN;
extern const Sifteo::AssetImage GraphemeO;
extern const Sifteo::AssetImage GraphemeP;
extern const Sifteo::AssetImage GraphemePP;
extern const Sifteo::AssetImage GraphemeQ;
extern const Sifteo::AssetImage GraphemeR;
extern const Sifteo::AssetImage GraphemeRR;
extern const Sifteo::AssetImage GraphemeWR;
extern const Sifteo::AssetImage GraphemeS;
extern const Sifteo::AssetImage GraphemeSS;
extern const Sifteo::AssetImage GraphemeCE;
extern const Sifteo::AssetImage GraphemeSE;
extern const Sifteo::AssetImage GraphemeSC;
extern const Sifteo::AssetImage GraphemeT;
extern const Sifteo::AssetImage GraphemeTT;
extern const Sifteo::AssetImage GraphemeU;
extern const Sifteo::AssetImage GraphemeV;
extern const Sifteo::AssetImage GraphemeVE;
extern const Sifteo::AssetImage GraphemeW;
extern const Sifteo::AssetImage GraphemeWH;
extern const Sifteo::AssetImage GraphemeX;
extern const Sifteo::AssetImage GraphemeY;
extern const Sifteo::AssetImage GraphemeZ;
extern const Sifteo::AssetImage GraphemeZZ;
extern const Sifteo::AssetImage GraphemeZE;
extern const Sifteo::AssetImage GraphemeSH;
extern const Sifteo::AssetImage GraphemeSI;
extern const Sifteo::AssetImage GraphemeTI;
extern const Sifteo::AssetImage GraphemeTCH;
extern const Sifteo::AssetImage GraphemeTH;
extern const Sifteo::AssetImage GraphemeNG;
extern const Sifteo::AssetImage GraphemeAB;
extern const Sifteo::AssetImage GraphemeAD;
extern const Sifteo::AssetImage GraphemeAG;
extern const Sifteo::AssetImage GraphemeAM;
extern const Sifteo::AssetImage GraphemeAN;
extern const Sifteo::AssetImage GraphemeAP;
extern const Sifteo::AssetImage GraphemeAT;
extern Sifteo::AssetGroup IconAssets;
extern const Sifteo::AssetImage Icon;
extern const Sifteo::PinnedAssetImage Bars[4];
extern const Sifteo::AssetAudio SfxAttach;
extern const Sifteo::AssetAudio SfxDetach;
extern const Sifteo::AssetAudio SfxConnect;
extern const Sifteo::AssetAudio PhonemeShortA;
extern const Sifteo::AssetAudio PhonemeShortE;
extern const Sifteo::AssetAudio PhonemeShortI;
extern const Sifteo::AssetAudio PhonemeShortO;
extern const Sifteo::AssetAudio PhonemeShortU;
extern const Sifteo::AssetAudio PhonemeK;
extern const Sifteo::AssetTracker Music;
