IconAssets = group{ quality=9.95 }
Icon = image{ "assets/icon.png" }

BootstrapAssets = group{ quality=9.9 }
BlackTile = image{ "assets/black.png", pinned=true }
Bars = {
	image{ "assets/bar_top.png", pinned=true },
	image{ "assets/bar_left.png", pinned=true },
	image{ "assets/bar_bottom.png", pinned=true },
	image{ "assets/bar_right.png", pinned=true }
}
Backgrounds = image{ { "assets/bg_sleep.png", "assets/bg_wake.png" } }
Alphabet = image{ {"assets/A.png", "assets/B.png", "assets/C.png", "assets/D.png", "assets/E.png", "assets/F.png", "assets/G.png", "assets/H.png", "assets/I.png", "assets/J.png", "assets/K.png", "assets/L.png", "assets/M.png", "assets/N.png", "assets/O.png", "assets/P.png", "assets/Q.png", "assets/R.png", "assets/S.png", "assets/T.png", "assets/U.png", "assets/V.png", "assets/W.png", "assets/X.png", "assets/Y.png", "assets/Z.png" } }

Music = tracker{ "assets/ultrasyd-toy_world.xm" } -- Toy World Is On Fire by Ultrasyd, Non-commercial License
SfxAttach = sound{ "assets/snap.wav" }
SfxDetach = sound{ "assets/pop.wav" }
SfxConnect = sound{ "assets/connect.raw" }

GraphemeA = image{ "assets/graphemes/a.png" }
GraphemeB = image{ "assets/graphemes/b.png" }
GraphemeBB = image{ "assets/graphemes/bb.png" }
GraphemeC = image{ "assets/graphemes/c.png" }
GraphemeCK = image{ "assets/graphemes/ck.png" }
GraphemeCH = image{ "assets/graphemes/ch.png" }
GraphemeD = image{ "assets/graphemes/d.png" }
GraphemeDD = image{ "assets/graphemes/dd.png" }
GraphemeE = image{ "assets/graphemes/e.png" }
GraphemeF = image{ "assets/graphemes/f.png" }
GraphemeFF = image{ "assets/graphemes/ff.png" }
GraphemePH = image{ "assets/graphemes/ph.png" }
GraphemeGH = image{ "assets/graphemes/gh.png" }
GraphemeG = image{ "assets/graphemes/g.png" }
GraphemeH = image{ "assets/graphemes/h.png" }
GraphemeI = image{ "assets/graphemes/i.png" }
GraphemeJ = image{ "assets/graphemes/j.png" }
GraphemeDGE = image{ "assets/graphemes/dge.png" }
GraphemeGE = image{ "assets/graphemes/ge.png" }
GraphemeK = image{ "assets/graphemes/k.png" }
GraphemeL = image{ "assets/graphemes/l.png" }
GraphemeLL = image{ "assets/graphemes/ll.png" }
GraphemeM = image{ "assets/graphemes/m.png" }
GraphemeMM = image{ "assets/graphemes/mm.png" }
GraphemeMB = image{ "assets/graphemes/mb.png" }
GraphemeN = image{ "assets/graphemes/n.png" }
GraphemeKN = image{ "assets/graphemes/kn.png" }
GraphemeO = image{ "assets/graphemes/o.png" }
GraphemeP = image{ "assets/graphemes/p.png" }
GraphemePP = image{ "assets/graphemes/pp.png" }
GraphemeQ = image{ "assets/graphemes/q.png" }
GraphemeR = image{ "assets/graphemes/r.png" }
GraphemeRR = image{ "assets/graphemes/rr.png" }
GraphemeWR = image{ "assets/graphemes/wr.png" }
GraphemeS = image{ "assets/graphemes/s.png" }
GraphemeSS = image{"assets/graphemes/ss.png"}
GraphemeCE = image{"assets/graphemes/ce.png" }
GraphemeSE = image{"assets/graphemes/se.png" }
GraphemeSC = image{"assets/graphemes/sc.png" }
GraphemeT = image{ "assets/graphemes/t.png" }
GraphemeTT = image{"assets/graphemes/tt.png" }
GraphemeU = image{ "assets/graphemes/u.png" }
GraphemeV = image{ "assets/graphemes/v.png" }
GraphemeVE = image{ "assets/graphemes/ve.png" }
GraphemeW = image{ "assets/graphemes/w.png" }
GraphemeWH = image{ "assets/graphemes/wh.png" }
GraphemeX = image{ "assets/graphemes/x.png" }
GraphemeY = image{ "assets/graphemes/y.png" }
GraphemeZ = image{ "assets/graphemes/z.png" }
GraphemeZZ = image{ "assets/graphemes/zz.png" }
GraphemeZE = image{ "assets/graphemes/ze.png" }
GraphemeSH = image{ "assets/graphemes/sh.png" }
GraphemeSI = image{ "assets/graphemes/si.png" }
GraphemeTI = image{ "assets/graphemes/ti.png" }
GraphemeTCH = image{ "assets/graphemes/tch.png" }
GraphemeTH = image{ "assets/graphemes/th.png" }
GraphemeNG = image{ "assets/graphemes/ng.png" }
GraphemeAB = image{ "assets/graphemes/ab.png" }
GraphemeAD = image{ "assets/graphemes/ad.png" }
GraphemeAG = image{ "assets/graphemes/ag.png" }
GraphemeAM = image{ "assets/graphemes/am.png" }
GraphemeAN = image{ "assets/graphemes/an.png" }
GraphemeAP = image{ "assets/graphemes/ap.png" }
GraphemeAT = image{ "assets/graphemes/at.png" }

PhonemeShortA = sound{ "assets/phonemes/a_short.wav" } 
PhonemeShortE = sound{ "assets/phonemes/e_short.wav" } 
PhonemeShortI = sound{ "assets/phonemes/i_short.wav" } 
PhonemeShortO = sound{ "assets/phonemes/o_short.wav" } 
PhonemeShortU = sound{ "assets/phonemes/u_short.wav" } 
PhonemeK = sound{ "assets/phonemes/e_short.wav" }
PhonemeB = sound{ "assets/phonemes/e_short.wav" }